# 深度學習入門

[郭耀仁](https://linktr.ee/yaojenkuo) | [簡歷](https://datainpoint.com/about.html) | <yaojenkuo@ntu.edu.tw> | 關務署

## 什麼是深度學習

- 深度學習是一種使用連續且多層的矩陣運算與激勵函數，從訓練資料進行模型係數最適化的方法。
- 深度學習是機器學習的一個分支。
- 以集合概念來說明的話，深度學習包含於機器學習之中，是機器學習集合的子集合。

## 什麼是機器學習：三個要素、一個但書

> A computer program is said to learn from experience E with respect to some class of tasks T and performance measure P if its performance at tasks in T, as measured by P, improves with experience E.

來源：[Machine Learning, Tom Mitchell, McGraw Hill, 1997](http://www.cs.cmu.edu/~tom/mlbook.html)

## 傳統透過電腦程式解決問題的方式

![](001.png)

來源：<https://www.coursera.org/learn/introduction-tensorflow>

## 給定規則 $w$ 以及資料 $X$，我們就可以定義出函數 $f$ 生成答案 $y$

\begin{equation}
y = f(X;w) = Xw
\end{equation}

## 以機器學習的電腦程式解決問題的方式示意圖

![](002.png)

來源：<https://www.coursera.org/learn/introduction-tensorflow>

## 給定答案 $y$ 以及資料 $X$，機器學習的電腦程式在最小化損失函數 $J$ 的前提下生成規則 $w$，進而獲得預測 $\hat{y}$

\begin{equation}
    \text{choose} \; w \in \mathbb{R^n} \; \text{where} \; w \; \text{minimizes} \; J(w) \\
\text{subject to} \; \hat{y} = h(X; w) = Xw \\
\text{where} \; J(w) \; \text{measures the loss between} \; y \; \text{and} \; \hat{y} \\
\end{equation}

## 給定答案 $y$、資料 $X$、活化函數 $g^{(i)}$，深度學習的電腦程式在最小化損失函數 $J$ 的前提下生成規則 $W^{(i)}$ 與誤差 $b^{(i)}$，進而獲得預測 $\hat{y}$ 

\begin{equation}
\text{choose} \; W^{(i)} \in \mathbb{R^{m \times n}} \; \text{and} \; b^{(i)} \in \mathbb{R^n} \\
\text{where} \; W^{(i)} \; \text{and} \; b^{(i)} \text{minimizes} \; J(W^{(i)}, b^{(i)}) \\
\text{subject to} \; \hat{y} = h(X; W^{(i)}, b^{(i)}, g^{(i)}) = \prod g^{(i)} ( A^{(i-1)}W^{(i)} + b^{(i)} ) \\
\text{where} \; A^{(0)} = XW^{(1)} + b^{(1)} \\
\text{where} \; i \in {\mathbb{Z^+}|\max(i) \geq 2} \\
\text{where} \; J(W^{(i)}, b^{(i)}) \; \text{measures the loss between} \; y \; \text{and} \; \hat{y}
\end{equation}

## 為何深度學習

- 機器學習要求先釐清特徵矩陣和目標向量之間的可能關聯。
- 當資料中提取出特徵這件事情成為與預測一樣困難的時候，機器學習就難以派上用場。
- 深度學習允許電腦程式將相對單純的輸入構建成複雜的函數映射系統，藉此讓使用者能在不釐清特徵矩陣與目標向量之間關聯的情況下進行預測。

## 深度學習的主要應用場景

- 深度學習在特定領域諸如影像分類、語音識別或機器翻譯等難以進行特徵工程的領域特別受到歡迎。
- 深度學習擅長的領域是人類相對於電腦程式容易執行的任務。
- 對人們來說影像分類、語音識別或語言翻譯是很直觀的事情，但對於電腦程式來說，解決這些問題的邏輯、規則都無法用程式語言描述。

## 深度學習的溯源

- Frank Rosenblatt 於 1957 年提出感知器（Perceptron），是深度學習模型的雛型。
- 感知器是一種由特徵 $x$、係數 $w$ 、誤差 $b$ 與階躍函數 $\chi$ 組合而成的函數。

\begin{equation}
\hat{y} = \chi(x^Tw + b) \; \text{where}\\
\chi(z) = 0, \; \text{if} \; z < 0 \\
\chi(z) = 1, \; \text{if} \; z \geq 0
\end{equation}

## 感知器與羅吉斯迴歸

- 羅吉斯迴歸較感知器多了 Sigmoid 函數的轉換才輸入階躍函數。
- 感知器之所以未能發揚光大，就是缺乏能將線性輸入 $w^Tx$ 轉換為非線性的活化函數（Activation function）。

\begin{equation}
\hat{y} = \chi(\sigma(x^Tw + b)) \; \text{where}\\
z = x^Tw + b \\
\sigma(z) = \frac{1}{1 + e^{-z}} \\
\chi(\sigma(z)) = 0, \; \text{if} \; \sigma(z) < 0.5 \\
\chi(\sigma(z)) = 1, \; \text{if} \; \sigma(z) \geq 0.5
\end{equation}

## 深度學習與機器學習的差異 

兩者同樣利用 $h$ 函數來逼近某個函數 $f$，但由於深度學習模型具備了層數的結構，需要近似的函數 $h$ 也成為了鏈結函數。

\begin{align}
\hat{y} &= h(X; W^{(i)}, b^{(i)}, g^{(i)}) \\
&= g^{(n)}( ... (g^{(2)}(g^{(1)}(XW^{(1)}  + b^{(1)})W^{(2)} + b^{(2)})...)W^{(n)} + b^{(n)})
\end{align}

## 深度學習模型的層數與單位數

- 層數 $l$：一個最基本的深度學習模型層數至少要有三層 $l \in \mathbb{Z^+}|l \geq 3$，輸入層、隱藏層與輸出層。
- 間隔數 $i$：如同植樹問題，層數減去 1 即為間隔數。
- 輸入層單位數：與特徵矩陣的一列觀測值 $x_i$ 的外型相同。
- 隱藏層單位數：隱藏層要有幾個神經元通常會以 $2^{n} \; , \; n \in \mathbb{Z^+}|n \geq 1$ 來自訂。
- 輸出層單位數：與目標向量的一列觀測值 $\hat{y_i}$ 的外型相同。

![](003.png)

## 深度學習模型的層數、單位數以及欲求解的係數與誤差

- 層數 $l$：$l = 3$
- 間隔數 $i$：$i = 2$
- 輸入層單位數：2
- 隱藏層單位數：4
- 輸出層單位數：1
- $W^{(1)} \in \mathbb{R^{2 \times 4}}, \; b^{(1)} \in \mathbb{R}^4$
- $W^{(2)} \in \mathbb{R^{4 \times 1}}, \; b^{(2)} \in \mathbb{R}^1$

![](004.png)

## 深度學習模型的層數、單位數以及欲求解的係數與誤差（續）

- 層數 $l$：$l = 4$
- 間隔數 $i$：$i = 3$
- 輸入層單位數：2
- 隱藏層一單位數：4
- 隱藏層二單位數：8
- 輸出層單位數：1
- $W^{(1)} \in \mathbb{R^{2 \times 4}}, \; b^{(1)} \in \mathbb{R}^4$
- $W^{(2)} \in \mathbb{R^{4 \times 8}}, \; b^{(2)} \in \mathbb{R}^8$
- $W^{(3)} \in \mathbb{R^{8 \times 1}}, \; b^{(3)} \in \mathbb{R}^1$

## 機器學習的電腦程式透過「梯度遞減」演算法在最小化損失函數 $J$ 的前提下生成規則 $w$

\begin{equation}
\text{for} \; \text{each} \; \text{epoch:} \\
w := w - \alpha \frac{\partial J}{\partial w} \\
\text{where} \; \alpha \in \mathbb{Z^+}|\alpha > 0
\end{equation}

## 深度學習的電腦程式透過反覆的「前向傳播」與「反向傳播」在最小化損失函數 $J$ 的前提下生成規則 $W^{(i)}$ 與誤差 $b^{(i)}$

\begin{equation}
\text{for} \; \text{each} \; \text{epoch:} \\
\hat{y} = \prod g^{(i)} ( A^{(i-1)}W^{(i)} + b^{(i)} ) \\
W^{(i)} := W^{(i)} - \alpha \frac{\partial J}{\partial W^{(i)}} \\
b^{(i)} := b^{(i)} - \alpha \frac{\partial J}{\partial b^{(i)}} \\
\text{where} \; \alpha \in \mathbb{Z^+}|\alpha > 0 \; \text{and} \; i \in \mathbb{Z^+}| \max(i) \geq 2 \\
\text{where} \; J(W^{(i)}, b^{(i)}) \; \text{measures the loss between} \; y \; \text{and} \; \hat{y}
\end{equation}

## 前向傳播與反向傳播

- 前向傳播的重點：
    - 矩陣的相乘與相加。
    - 建構模型的層數、單位數、欲求解的係數與誤差之外型。
- 反向傳播的重點：
    - 鏈結函數的偏微分仰賴連鎖法則。
    - 對數函數與活化函數的微分。

## 前向傳播

## 前向傳播：以最精簡的深度學習模型為例

- 一個最精簡的深度學習模型會有輸入層、隱藏層與輸出層至少三層。
- 透過各層之間的單位數連接，可以得到 $W^{(i)}$ 與 $b^{(i)}$ 的外型。
- 每層都是由前一層的輸出與當層的權重與誤差結合，透過活化函數 $g$ 轉換，然後再成為下一層的輸入。

## 前向傳播（Forward propagation）就是矩陣的相乘與相加

\begin{align}
Z^{(1)} &= W^{(1)}A^{(0)} + b^{(1)} = XW^{(1)} + b^{(1)} \\
A^{(1)} &= g^{(1)}(Z^{(1)}) \\
Z^{(2)} &= A^{(1)}W^{(2)} + b^{(2)} \\
A^{(2)} &= g^{(2)}(Z^{(2)}) \\ 
\hat{y} &= A^{(2)}
\end{align}

![](003.png)

## 矩陣若要順利相乘與相加需注意外型

\begin{equation}
X \in \mathbb{R^{m \times 2}} \\
W^{(1)} \in \mathbb{R^{2 \times 4}}, \; b^{(1)} \in \mathbb{R}^4 \\
Z^{(1)} \in \mathbb{R^{m \times 4}}, \; A^{(1)} \in \mathbb{R^{m \times 4}} \\
W^{(2)} \in \mathbb{R^{4 \times 1}}, \; b^{(2)} \in \mathbb{R}^1 \\
Z^{(2)} \in \mathbb{R^{m \times 1}}, \; A^{(2)} \in \mathbb{R^{m \times 1}} \\
\hat{y} \in \mathbb{R}^m
\end{equation}

## 反向傳播

## 每回訓練迭代

- 完成一次前向傳播，特徵矩陣 $X$ 就會依賴當下的權重 $W^{(i)}$ 和誤差 $b^{(i)}$ 計算而得 $\hat{y}$
- 這時就能夠計算 $y$ 與 $\hat{y}$ 之間的誤差量值。

\begin{equation}
\text{for} \; \text{each} \; \text{epoch:} \\
\hat{y} = \prod g^{(i)} ( A^{(i-1)}W^{(i)} + b^{(i)} )
\end{equation}

## 評估數值預測的誤差

\begin{align}
J(W^{(i)}, b^{(i)}) &= \frac{1}{m} \parallel y - \hat{y} \; \parallel^2 \\
&= \frac{1}{m} \parallel y - h(X; W^{(i)}, b^{(i)}) \; \parallel^2
\end{align}

## 評估類別預測的誤差

\begin{align}
J(W^{(i)}, b^{(i)}, g^{(i)}) &= \frac{1}{m}(-ylog(\hat{y}) - (1-y)log(1-\hat{y})) \\
&= \frac{1}{m}(-ylog(h(X; W^{(i)}, b^{(i)}, g^{(i)})) - (1-y)log(1-h(X; W^{(i)}, b^{(i)}, g^{(i)})))
\end{align}

## 反向傳播：深度學習模型的梯度遞減演算法

分別計算 $J(W^{(i)}, b^{i})$ 關於各層的權重與誤差之偏微分，並且返回各層決定該如何更新權重與誤差，這樣的技巧稱為「反向傳播」（Backpropagation）。

\begin{equation}
\text{for} \; \text{each} \; \text{epoch:} \\
W^{(i)} := W^{(i)} - \alpha \frac{\partial J(W^{(i)}, b^{(i)}) }{\partial W^{(i)}} \\
b^{(i)} := b^{(i)} - \alpha \frac{\partial J(W^{(i)}, b^{(i)}) }{\partial b^{(i)}} \\
\text{where} \; \alpha \in \mathbb{Z^+}|\alpha > 0 \\
\text{where} \; J(W^{(i)}, b^{(i)}) \; \text{measures the loss between} \; y \; \text{and} \; \hat{y}
\end{equation}

## 以一個最精簡的深度學習模型為例

\begin{align}
Z^{(1)} &= W^{(1)}A^{(0)} + b^{(1)} = XW^{(1)} + b^{(1)} \\
A^{(1)} &= g^{(1)}(Z^{(1)}) \\
Z^{(2)} &= A^{(1)}W^{(2)} + b^{(2)} \\
A^{(2)} &= g^{(2)}(Z^{(2)}) \\ 
\hat{y} &= A^{(2)}
\end{align}

## 反向傳播的重點：連鎖法則

- 應用連鎖法則（Chain rule）求解 $J$ 關於各層的權重與誤差之偏微分。
- 以一個最精簡的深度學習模型為例，會先計算 $W^{(2)}$ 以及 $b^{(2)}$ 的更新值。

\begin{align}
\frac{\partial J}{\partial W^{(2)}} = \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial W^{(2)}} \\
\frac{\partial J}{\partial b^{(2)}} = \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial b^{(2)}}
\end{align}

## 反向傳播的重點：對數函數與活化函數的微分

- 損失函數以交叉熵（Cross entropy）為例。
- 活化函數以 Sigmoid 函數為例。

\begin{equation}
\frac{d}{dx}log(x) = \frac{1}{x} \\
\frac{d}{dx}log(1 - x) = \frac{-1}{1 - x} \\
\frac{d}{dx}\sigma(x)=\sigma(x) ( 1 - \sigma(x) )
\end{equation}

## 將連鎖法則的部分拆開來計算：$\partial J / \partial A^{(2)}$

損失函數以交叉熵（Cross entropy）為例。

\begin{align}
\frac{\partial J}{\partial A^{(2)}} &= \frac{\partial}{\partial A^{(2)}} \left( \frac{1}{m} (-ylog(A^{(2)}) - (1 - y)log(1 - A^{(2)})) \right) \\
&= \frac{1}{m} \left( -y\frac{1}{A^{(2)}} - (1-y)\frac{-1}{1 - A^{(2)}} \right) \\
&= \frac{1}{m} \left( \frac{-y(1 - A^{(2)}) - (y-1)A^{(2)} }{A^{(2)} (1 - A^{(2)})} \right) \\
&= \frac{1}{m} \left( \frac{-y + yA^{(2)} - yA^{(2)} +A^{(2)} }{A^{(2)} (1 - A^{(2)})} \right) \\
&= \frac{1}{m} \left( \frac{A^{(2)} - y }{A^{(2)} (1 - A^{(2)})} \right)
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial A^{(2)} / \partial Z^{(2)}$

活化函數以 Sigmoid 函數為例。

\begin{align}
\frac{\partial A^{(2)}}{\partial Z^{(2)}} &= \frac{\partial}{\partial Z^{(2)}} \left( g^{(2)}(Z^{(2)}) \right) \\
&= \frac{\partial}{\partial Z^{(2)}} \left( \sigma(Z^{(2)}) \right) \\
&= \sigma(Z^{(2)})(1 - \sigma(Z^{(2)})) \\
&= {A^{(2)} (1 - A^{(2)})} 
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial Z^{(2)} / \partial W^{(2)}$

\begin{align}
\frac{\partial Z^{(2)}}{\partial W^{(2)}} &= \frac{\partial}{\partial W^{(2)}} \left( A^{(1)}W^{(2)} + b^{(2)} \right) \\
&= A^{(1)} 
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial Z^{(2)} / \partial b^{(2)}$

\begin{align}
\frac{\partial Z^{(2)}}{\partial b^{(2)}} &= \frac{\partial}{\partial b^{(2)}} \left( A^{(1)}W^{(2)} + b^{(2)} \right) \\
&= 1 
\end{align}

## 將拆開計算的部分相乘：如何更新 $W^{(2)}$ 與 $b^{(2)}$

\begin{align}
\frac{\partial J}{\partial W^{(2)}} &= \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial W^{(2)}} \\
&= \frac{1}{m} \left( \frac{A^{(2)} - y }{A^{(2)} (1 - A^{(2)})} \right) \left( {A^{(2)} (1 - A^{(2)})} \right) A^{(1)} \\
&= \frac{1}{m} \left( A^{(2)} - y \right) A^{(1)} \\
\frac{\partial J}{\partial b^{(2)}} &= \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial b^{(2)}} \\
&= \frac{1}{m} \left( A^{(2)} - y \right)
\end{align}

## 反向傳播的重點：連鎖法則（續）

計算 $W^{(2)}$ 以及 $b^{(2)}$ 的更新值後，再計算 $W^{(1)}$ 以及 $b^{(1)}$ 的更新值。

\begin{align}
\frac{\partial J}{\partial W^{(1)}} = \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial A^{(1)}} \frac{\partial A^{(1)}}{\partial Z^{(1)}} \frac{\partial Z^{(1)}}{\partial W^{(1)}} \\
\frac{\partial J}{\partial b^{(1)}} = \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial A^{(1)}} \frac{\partial A^{(1)}}{\partial Z^{(1)}} \frac{\partial Z^{(1)}}{\partial b^{(1)}}
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial Z^{(2)} / \partial A^{(1)}$

\begin{align}
\frac{\partial Z^{(2)}}{\partial A^{(1)}} &= \frac{\partial}{\partial A^{(1)}} \left( A^{(1)}W^{(2)} + b^{(2)} \right) \\
&= W^{(2)}
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial A^{(1)} / \partial Z^{(1)}$

活化函數以 Sigmoid 函數為例。

\begin{align}
\frac{\partial A^{(1)}}{\partial Z^{(1)}} &= \frac{\partial}{\partial Z^{(1)}} \left( g^{(1)}(Z^{(1)}) \right) \\
&= \frac{\partial}{\partial Z^{(1)}} \left( \sigma(Z^{(1)}) \right) \\
&= \sigma(Z^{(1)})(1 - \sigma(Z^{(1)})) \\
&= A^{(1)}(1 - A^{(1)})
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial Z^{(1)} / \partial W^{(1)}$

\begin{align}
\frac{\partial Z^{(1)}}{\partial W^{(1)}} &= \frac{\partial}{\partial W^{(1)}} \left( XW^{(1)} + b^{(1)} \right) \\
&= X
\end{align}

## 將連鎖法則的部分拆開來計算：$\partial Z^{(1)} / \partial b^{(1)}$

\begin{align}
\frac{\partial Z^{(1)}}{\partial b^{(1)}} &= \frac{\partial}{\partial b^{(1)}} \left( XW^{(1)} + b^{(1)} \right) \\
&= 1
\end{align}

## 將拆開計算的部分相乘：如何更新 $W^{(1)}$ 與 $b^{(1)}$

\begin{align}
\frac{\partial J}{\partial W^{(1)}} &= \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial A^{(1)}} \frac{\partial A^{(1)}}{\partial Z^{(1)}} \frac{\partial Z^{(1)}}{\partial W^{(1)}} \\
&= \frac{1}{m} \left( \frac{A^{(2)} -y }{A^{(2)} (1 - A^{(2)})} \right) \left( {A^{(2)} (1 - A^{(2)})} \right) W^{(2)} \left( A^{(1)}(1 - A^{(1)}) \right) X \\
&= \frac{1}{m} \left( A^{(2)} -y \right) W^{(2)} \left( A^{(1)}(1 - A^{(1)}) \right) X \\
\frac{\partial J}{\partial b^{(1)}} &= \frac{\partial J}{\partial A^{(2)}} \frac{\partial A^{(2)}}{\partial Z^{(2)}} \frac{\partial Z^{(2)}}{\partial A^{(1)}} \frac{\partial A^{(1)}}{\partial Z^{(1)}} \frac{\partial Z^{(1)}}{\partial b^{(1)}} \\
&= \frac{1}{m} \left( A^{(2)} -y \right) W^{(2)} \left( A^{(1)}(1 - A^{(1)}) \right)
\end{align}

## 深度學習框架

## 深度學習框架：Keras 與 PyTorch

- Keras 由 [François Chollet](https://twitter.com/fchollet) 開發，於 2015 年 3 月以開源專案的形式發行。
- PyTorch 由 Meta AI（當時的 Facebook）開發，於 2016 年 9 月以開源專案的形式發行。

## 深度學習框架的受歡迎程度

![](005.png)

來源：<https://trends.stackoverflow.co/?tags=keras,tensorflow,pytorch,caffe>

## 深度學習框架使用的步驟

1. 定義訓練資料。
2. 定義深度學習模型的結構：層數、每層的單位數以及活化函數。
3. 定義評估指標：選擇用來衡量 $y$ 與 $\hat{y}$ 之間誤差的函數、更新 $W^{(i)}$  與的演算方法以及評估 $h$ 的指標。
4. 最適化：迭代訓練資料。

## Keras 與 PyTorch 使用的差異

- Keras 採用函數程式設計。
- PyTorch 採用物件導向程式設計。

## 機器學習與深度學習的哈囉世界

- [Titanic](https://www.kaggle.com/competitions/titanic)
- [Spaceship Titanic](https://www.kaggle.com/competitions/spaceship-titanic)
- [MNIST](https://www.kaggle.com/competitions/digit-recognizer)
- [Fashion MNIST](https://www.kaggle.com/datasets/zalando-research/fashionmnist)

## 使用 Keras 利用 Titanic 資料中的數值欄位來預測 `Survived`

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras

2024-05-09 13:01:24.852279: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# 定義訓練資料
train = pd.read_csv("titanic/train.csv")
mean_age = train["Age"].mean()
train["Age"] = train["Age"].fillna(mean_age)
X = train[["Pclass", "Age", "SibSp", "Parch", "Fare"]].values
y = train["Survived"].values
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)

In [3]:
# 定義深度學習模型的結構
model = keras.models.Sequential([
    keras.layers.Input((X_train.shape[1],)),
    keras.layers.Dense(8, activation='sigmoid'),
    keras.layers.Dense(1, activation='sigmoid')
], name="titanic_nn")

## 定義深度學習模型的結構

- $W^{(1)} \in \mathbb{R^{5 \times 8}}$
- $b^{(1)} \in \mathbb{R}^8$
- $W^{(2)} \in \mathbb{R^{8 \times 1}}$
- $b^{(2)} \in \mathbb{R}^1$
- 共計有 $(5 \times 8 + 8) + (8 \times 1 + 1) = 57$ 個係數、偏差要進行最適化。

In [4]:
model.summary()

Model: "titanic_nn"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 57 (228.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# 定義評估指標
model.compile(optimizer="SGD", loss='binary_crossentropy', metrics=['accuracy'])

In [6]:
# 最適化
model.fit(X_train, y_train, 
          validation_data=(X_valid, y_valid),
          epochs=5)

Epoch 1/5
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6330 - loss: 0.7608 - val_accuracy: 0.5932 - val_loss: 0.7305
Epoch 2/5
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6599 - loss: 0.6569 - val_accuracy: 0.5932 - val_loss: 0.6847
Epoch 3/5
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6291 - loss: 0.6796 - val_accuracy: 0.5932 - val_loss: 0.6600
Epoch 4/5
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6500 - loss: 0.6444 - val_accuracy: 0.5932 - val_loss: 0.6474
Epoch 5/5
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6259 - loss: 0.6474 - val_accuracy: 0.5932 - val_loss: 0.6419


In [7]:
# 取得係數與誤差
W1, b1, W2, b2 = model.get_weights()
print(W1.shape)
print(b1.shape)
print(W2.shape)
print(b2.shape)

(5, 8)
(8,)
(8, 1)
(1,)


## 使用 PyTorch 利用 Titanic 資料中的數值欄位來預測 `Survived`

In [8]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [9]:
# 定義訓練資料
class TitanicDataset(Dataset):
    def __init__(self, file_path):
        self.df = pd.read_csv(file_path)
        mean_age = self.df["Age"].mean()
        self.df["Age"] = self.df["Age"].fillna(mean_age)
        target_features = self.df[["Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]].values.astype(np.float32)
        target_features = torch.from_numpy(target_features)
        self.target_features = target_features
    def __len__(self):
        return self.target_features.shape[0]
    def __getitem__(self, idx):
        n_features = self.target_features.shape[1] - 1
        features = self.target_features[idx, 1:].reshape(-1, n_features)
        target = self.target_features[idx, 0].reshape(-1, 1)
        return features, target

In [10]:
batch_size = 1
training_data = TitanicDataset("titanic/train.csv")
train_dataloader = DataLoader(training_data, batch_size=batch_size)

In [11]:
# 定義深度學習模型的結構
class TitanicNN(nn.Module):
    def __init__(self):
        super(TitanicNN, self).__init__()
        self.fc1 = nn.Linear(5, 8)
        self.fc2 = nn.Linear(8, 1)       
    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x
model = TitanicNN()

## 定義深度學習模型的結構

- $W^{(1)} \in \mathbb{R^{5 \times 8}}$
- $b^{(1)} \in \mathbb{R}^8$
- $W^{(2)} \in \mathbb{R^{8 \times 1}}$
- $b^{(2)} \in \mathbb{R}^1$
- 共計有 $(5 \times 8 + 8) + (8 \times 1 + 1) = 57$ 個係數、偏差要進行最適化。

In [12]:
print(model)
number_of_params = 0
for p in model.parameters():
    print(p.numel())
    number_of_params += p.numel()
print(f"Total parameters to optimize: {number_of_params}")

TitanicNN(
  (fc1): Linear(in_features=5, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=1, bias=True)
)
40
8
8
1
Total parameters to optimize: 57


In [13]:
# 定義評估指標
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [14]:
# 最適化
def train(dataloader, model, loss_function, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()
        y_hat = model(X)
        loss = loss_function(y_hat, y)
        loss.backward()
        optimizer.step()
        if batch % 100 == 0:
            loss = loss.item()
            print(f"loss: {loss}")

In [15]:
epochs = 5
for epoch in range(epochs):
    print(f"Epoch {epoch + 1}\n-------------------------------")
    train(train_dataloader, model, loss_function, optimizer)

Epoch 1
-------------------------------
loss: 0.6988667249679565
loss: 0.6775882244110107
loss: 0.597796618938446
loss: 0.8385881185531616
loss: 0.830159068107605
loss: 0.4967316687107086
loss: 0.7135754227638245
loss: 0.8459523320198059
loss: 0.4087979197502136
Epoch 2
-------------------------------
loss: 0.41832900047302246
loss: 0.41495180130004883
loss: 0.38711604475975037
loss: 1.1325678825378418
loss: 1.114043951034546
loss: 0.4117561876773834
loss: 0.7214779257774353
loss: 0.8223960995674133
loss: 0.3648863732814789
Epoch 3
-------------------------------
loss: 0.37337595224380493
loss: 0.3703485429286957
loss: 0.3546156883239746
loss: 1.2055164575576782
loss: 1.1895211935043335
loss: 0.39478039741516113
loss: 0.7040594220161438
loss: 0.6750205159187317
loss: 0.3475863039493561
Epoch 4
-------------------------------
loss: 0.35664883255958557
loss: 0.3524397015571594
loss: 0.3392660915851593
loss: 1.2440681457519531
loss: 1.229285717010498
loss: 0.3862099349498749
loss: 0.68823

In [16]:
# 取得係數與誤差
W1, b1, W2, b2 = [p.detach().numpy() for p in model.parameters()]
print(W1.T.shape)
print(b1.shape)
print(W2.T.shape)
print(b2.shape)

(5, 8)
(8,)
(8, 1)
(1,)


## 使用 Keras 利用 MNIST 資料中的所有欄位來預測 `label`

In [17]:
# 定義訓練資料
train = pd.read_csv("mnist/train.csv")
X = train.iloc[:, 1:].values
y = train["label"].values
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
w, h = 28, 28
X_train = X_train.reshape(X_train.shape[0], w*h)
X_valid = X_valid.reshape(X_valid.shape[0], w*h)
y_train = keras.utils.to_categorical(y_train, 10) # one-hot encoding
y_valid = keras.utils.to_categorical(y_valid, 10) # one-hot encoding

In [19]:
# 定義深度學習模型的結構
model = keras.models.Sequential([
    keras.layers.Input((784,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
], name="mnist_nn")

## 定義深度學習模型的結構

- $W^{(1)} \in \mathbb{R^{784 \times 64}}$
- $b^{(1)} \in \mathbb{R}^{64}$
- $W^{(2)} \in \mathbb{R^{64 \times 64}}$
- $b^{(2)} \in \mathbb{R}^{64}$
- $W^{(3)} \in \mathbb{R^{64 \times 10}}$
- $b^{(3)} \in \mathbb{R}^{10}$
- 共計有 $(784 \times 64 + 64) + (64 \times 64 + 64) + (64 \times 10 + 10) = 55050 $ 個係數、偏差要進行最適化。

In [20]:
print((784*64 + 64) + (64*64 + 64) + (64 * 10 + 10))

55050


In [21]:
model.summary()

Model: "mnist_nn"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 64)             │        50,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55,050 (215.04 KB)

 Trainable params: 55,050 (215.04 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# 定義評估指標
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
# 最適化
model.fit(X_train, y_train, 
          validation_data=(X_valid, y_valid),
          epochs=5)

Epoch 1/5
880/880 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7082 - loss: 7.8351 - val_accuracy: 0.8701 - val_loss: 0.7318
Epoch 2/5
880/880 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8861 - loss: 0.5791 - val_accuracy: 0.8881 - val_loss: 0.5208
Epoch 3/5
880/880 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9110 - loss: 0.3898 - val_accuracy: 0.9040 - val_loss: 0.4770
Epoch 4/5
880/880 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9241 - loss: 0.3106 - val_accuracy: 0.9121 - val_loss: 0.4298
Epoch 5/5
880/880 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9319 - loss: 0.2674 - val_accuracy: 0.9157 - val_loss: 0.3490


In [24]:
# 取得係數與誤差
W1, b1, W2, b2, W3, b3 = model.get_weights()
print(W1.shape)
print(b1.shape)
print(W2.shape)
print(b2.shape)
print(W3.shape)
print(b3.shape)

(784, 64)
(64,)
(64, 64)
(64,)
(64, 10)
(10,)


## 使用 PyTorch 利用 MNIST 資料中的所有欄位來預測 `label`

In [25]:
from sklearn.preprocessing import OneHotEncoder

# 定義訓練資料
class MnistDataset(Dataset):
    def __init__(self, file_path):
        self.df = pd.read_csv(file_path)
        ohe = OneHotEncoder(sparse_output=False)
        y = self.df["label"].values.reshape(-1, 1)
        y_ohe = ohe.fit_transform(y)
        self.targets = y_ohe.astype("float32")
        self.features = self.df.loc[:, "pixel0":"pixel783"].values.astype("float32")
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self, idx):
        return  self.features[idx, :], self.targets[idx, :]

In [26]:
batch_size = 64
training_data = MnistDataset("mnist/train.csv")
train_dataloader = DataLoader(training_data, batch_size=batch_size)

In [27]:
# 定義深度學習模型的結構
class MnistNN(nn.Module):
    def __init__(self):
        super(MnistNN, self).__init__()
        self.fc1 = nn.Linear(784, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 10)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x
model = MnistNN()

## 定義深度學習模型的結構

- $W^{(1)} \in \mathbb{R^{784 \times 64}}$
- $b^{(1)} \in \mathbb{R}^{64}$
- $W^{(2)} \in \mathbb{R^{64 \times 64}}$
- $b^{(2)} \in \mathbb{R}^{64}$
- $W^{(3)} \in \mathbb{R^{64 \times 10}}$
- $b^{(3)} \in \mathbb{R}^{10}$
- 共計有 $(784 \times 64 + 64) + (64 \times 64 + 64) + (64 \times 10 + 10) = 55050 $ 個係數、偏差要進行最適化。

In [28]:
print((784*64 + 64) + (64*64 + 64) + (64 * 10 + 10))

55050


In [29]:
print(model)
number_of_params = 0
for p in model.parameters():
    print(p.numel())
    number_of_params += p.numel()
print(f"Total parameters to optimize: {number_of_params}")

MnistNN(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=10, bias=True)
)
50176
64
4096
64
640
10
Total parameters to optimize: 55050


In [30]:
# 定義評估指標
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [31]:
# 最適化
def train(dataloader, model, loss_function, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()
        y_hat = model(X)
        loss = loss_function(y_hat, y)
        loss.backward()
        optimizer.step()
        if batch % 100 == 0:
            loss = loss.item()
            print(f"loss: {loss}")

In [32]:
epochs = 5
for epoch in range(epochs):
    print(f"Epoch {epoch + 1}\n-------------------------------")
    train(train_dataloader, model, loss_function, optimizer)

Epoch 1
-------------------------------
loss: 11.999723434448242
loss: 0.2209353744983673
loss: 0.46236667037010193
loss: 0.1490744650363922
loss: 0.27251148223876953
loss: 0.22566816210746765
loss: 0.01894434168934822
Epoch 2
-------------------------------
loss: 0.14670045673847198
loss: 0.06375771760940552
loss: 0.2502889335155487
loss: 0.10088138282299042
loss: 0.15793024003505707
loss: 0.14483611285686493
loss: 0.0098368925973773
Epoch 3
-------------------------------
loss: 0.0818667784333229
loss: 0.0303439199924469
loss: 0.08755240589380264
loss: 0.1427709460258484
loss: 0.2853507995605469
loss: 0.13332760334014893
loss: 0.003615599824115634
Epoch 4
-------------------------------
loss: 0.1568651795387268
loss: 0.02838054858148098
loss: 0.09189514070749283
loss: 0.0904645100235939
loss: 0.10240612924098969
loss: 0.10794302076101303
loss: 0.020528525114059448
Epoch 5
-------------------------------
loss: 0.04833913967013359
loss: 0.027621958404779434
loss: 0.2847987413406372
los

In [33]:
# 取得係數與誤差
W1, b1, W2, b2, W3, b3 = [p.detach().numpy() for p in model.parameters()]
print(W1.T.shape)
print(b1.shape)
print(W2.T.shape)
print(b2.shape)
print(W3.T.shape)
print(b3.shape)

(784, 64)
(64,)
(64, 64)
(64,)
(64, 10)
(10,)
